mdapi/objects/Galaxy__c.object
<CustomObject>
    <label>Galaxy</label>
    <nameField>
        <label>Galaxy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Galaxies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/Star__c.object
<CustomObject>
    <description>Stars in the Galaxy</description>
    <fields>
        <fullName>Galaxy__c</fullName>
        <description>Galaxy in which the Star resides</description>
        <inlineHelpText>Galaxy in which the Star resides</inlineHelpText>
        <label>Galaxy</label>
        <referenceTo>Galaxy__c</referenceTo>
        <relationshipLabel>Stars</relationshipLabel>
        <relationshipName>Stars</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Star</label>
    <nameField>
        <label>Star Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/classes/GalaxyAddExtension.cls
/*
 * GalaxyAddExtension
 * Override Galaxy New Button
 * Allow entry of a Galaxy along with a few stars
 */
public class GalaxyAddExtension {
    
    public Galaxy__c galaxy { get; set; }
    public List<Star__c> stars { get; set; }

    // Default number of stars to show
    private final Integer STAR_COUNT = 10;
        
	// Constructor - Initialize galaxy and stars
    public GalaxyAddExtension( ApexPages.StandardController controller) {
        galaxy = (Galaxy__c)controller.getRecord();
        stars = new List<Star__c>();
        for ( Integer i = 0 ; i < STAR_COUNT ; i++) {
            stars.add( new Star__c());
        }
        
    }
    
	// Save Method
    /*
     * The Save method will save any star with a name along with the Galaxy Id
     */
    public PageReference onSave() {
		// Don't save empty records
        if ( galaxy.Name == null ) {
            ApexPages.addMessage( new ApexPages.Message( ApexPages.Severity.ERROR, 'Galaxy Name is required'));
            return null;
        }
        insert galaxy;
        
		// Check for stars
        List<Star__c> goodStars = new List<Star__c>();
        for ( Star__c star : stars) {
            if ( star.Name != null ) {
                star.Galaxy__c = galaxy.Id;
                goodStars.add( star);
            }
        }
        insert goodStars;

		// Redirect to Galaxy View        
        return new PageReference( '/' + galaxy.Id);
    }

	// Cancel - Redirect to default Galaxy Page
    public PageReference onCancel() {
        return new PageReference( '/' + Galaxy__c.sObjectType.getDescribe().getKeyPrefix() + '/o');
    }
}